# which benchmarks to run
benchmarks = '../../benchmarks/**/*.bril'
# how to extract the performance metric from stderr
extract = 'total_dyn_inst: (\d+)'

[runs.baseline]
pipeline = [
  "bril2json",
  "brili -p {args}",
]

[runs.tdce]
pipeline = [
  "bril2json",
  "python3 remove_nops.py",
  "python3 tdce.py",
  "brili -p {args}",
]

[runs.lvn]
pipeline = [
  "bril2json",
  "python3 remove_nops.py",
  "python3 lvn.py",
  "brili -p {args}",
]

[runs.test]
pipeline = [
  "bril2json",
  "python3 remove_nops.py",
  "python3 tdce.py",
  "python3 lvn.py",
  "python3 tdce.py",
  "python3 lvn.py",
  "python3 tdce.py",
  "python3 lvn.py",
  "python3 tdce.py",
  "brili -p {args}",
]
