# which benchmarks to run
benchmarks = '../../benchmarks/**/*.bril'
# how to extract the performance metric from stderr
extract = 'total_dyn_inst: (\d+)'
timeout = 60

[runs.baseline]
pipeline = [
  "bril2json",
  "brili -p {args}",
]

[runs.remove_nops]
pipeline = [
  "bril2json",
  "python3 remove_nops.py",
  "brili -p {args}",
]

[runs.dataflow]
pipeline = [
  "bril2json",
  "python3 remove_nops.py",
  "python3 dataflow.py",
  "python3 remove_nops.py",
  "brili -p {args}",
]
